AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customer-service-lambda

Resources:
  CustomerServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 60
      Environment:
        Vatiables:
          username_path: "/dev/rds/username"
          password_path: "/dev/rds/pass"
          host_path: "/dev/rds/dbhost"
          db_name: "roomy"
      Events:
        GetCustomerListServiceById:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer
            Method: get
        GetCustomerServiceById:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer/{id}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomerServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for customer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customer/"
  CustomerServiceFunction:
    Description: "Customer Service Lambda Function ARN"
    Value: !GetAtt CustomerServiceFunction.Arn
  CustomerServiceFunctionIamRole:
    Description: "Implicit IAM Role created for customer function"
    Value: !GetAtt CustomerServiceFunctionRole.Arn
